#!/bin/bash
# Builds AeroSpace with patches/*.patch applied; with --install, swaps it into
# /Applications/AeroSpace.app (the original bundle is backed up first).
#
# switch-flicker.patch: on a workspace switch AeroSpace moves every window via
# the accessibility API, asynchronously on one thread per app, and raises the
# focused window last. So a switch could show an empty desktop (old windows
# hidden before the new ones arrived) or the wrong window on top for a frame.
# The patch raises + places the target window before anything else is queued
# (and, in accordion layouts, lets its app finish that before the siblings are
# placed, ≤100ms), and hides the old windows only once the new ones are in
# place (≤150ms).
#
# Signing is ad-hoc (no certificate needed), so macOS asks for Accessibility
# again after every install: System Settings → Privacy & Security →
# Accessibility → AeroSpace.
#
# Usage: ./build.sh [--install] [git-ref]
#   default ref: the commit of the installed aerospace CLI
set -euo pipefail

install=0
if [[ "${1:-}" == "--install" ]]; then install=1; shift; fi

APP=/Applications/AeroSpace.app
BACKUP="$HOME/.cache/aerospace-original.app"
SRC="$HOME/.cache/aerospace-src"
DIR="$(cd "$(dirname "$0")" && pwd)"

# version + commit of the installed (brew) client, so client and server match
read -r _ _ _ _ VERSION HASH < <(aerospace --version | head -1)
REF="${1:-$HASH}"

if [[ ! -d "$SRC/.git" ]]; then
  git clone -q https://github.com/nikitabobko/AeroSpace "$SRC"
fi
git -C "$SRC" fetch -q origin "$REF" 2>/dev/null || git -C "$SRC" fetch -q origin
git -C "$SRC" checkout -q --force "$REF"
git -C "$SRC" clean -qfdx -e .build

for p in "$DIR"/*.patch; do
  git -C "$SRC" apply "$p"
done

cat > "$SRC/Sources/Common/versionGenerated.swift" <<EOF
// FILE IS GENERATED BY generate.sh
public let aeroSpaceAppVersion = "$VERSION"
EOF
cat > "$SRC/Sources/Common/gitHashGenerated.swift" <<EOF
// FILE IS GENERATED BY generate.sh
public let gitHash = "$(git -C "$SRC" rev-parse HEAD)"
public let gitShortHash = "$(git -C "$SRC" rev-parse --short HEAD)"
EOF

# Command Line Tools are enough (no Xcode license needed)
(cd "$SRC" && env -u DEVELOPER_DIR swift build -c release --product AeroSpaceApp 2>&1 | grep -E "error|Build of product") || true
BIN="$SRC/.build/release/AeroSpaceApp"
[[ -x "$BIN" ]] || { echo "build failed" >&2; exit 1; }
echo "built $BIN ($VERSION + patches)"

[[ $install == 1 ]] || exit 0

# A bundle signed by upstream is pristine: (re)take the backup from it.
signature="$(codesign -dvv "$APP" 2>&1 || true)"
if [[ "$signature" == *"Authority=aerospace-codesign-certificate"* ]]; then
  rm -rf "$BACKUP" && cp -R "$APP" "$BACKUP"
fi
[[ -d "$BACKUP" ]] || { echo "no pristine AeroSpace.app to build on" >&2; exit 1; }

STAGE="$(mktemp -d)/AeroSpace.app"
cp -R "$BACKUP" "$STAGE"
cp "$BIN" "$STAGE/Contents/MacOS/AeroSpace"
codesign --force --sign - "$STAGE" 2>/dev/null
codesign --verify --deep --strict "$STAGE"

osascript -e 'quit app "AeroSpace"' 2>/dev/null || true
for _ in {1..50}; do pgrep -xq AeroSpace || break; sleep 0.1; done
pkill -x AeroSpace 2>/dev/null || true

rm -rf "$APP"
mv "$STAGE" "$APP"
# the old grant belongs to a different signature; start clean so macOS asks again
tccutil reset Accessibility bobko.aerospace >/dev/null 2>&1 || true
open "$APP"
echo "installed $APP — grant Accessibility to AeroSpace when macOS asks"
